### ISSUE TITLE
Auto upload / monitor clipboard

### ISSUE THREAD

**Issue by wamatt** [tangphillip/Imgur-Uploader#1]
Superb little app Phillip.

Quick suggestion, would be awesome if it auto-uploaded to Imgur when an image was on the clipboard, and the repasted the link to the clipboard.

http://tinygrab.com/ has that functionality, but it's closed source.

**Comment by tangphillip** [comment]
Unfortunately, this feature would require a daemon running all the time, monitoring the pasteboard. Given that we don't have a daemon at all right now, I think this is out of scope for the project.

**Comment by Octolus** [comment]
Hello,

Would it be possible to do the following?

- I take a screenshot
- The screenshot gets placed in specific folder
- The workflow detects it, uploads and adds to clipboard?

@tangphillip

**Comment by tangphillip** [comment]
Again, this is out of scope for the project. Feel free to write your own script using macOS's folder actions, or something like `inotify-tools` or `watch`.
