### ISSUE TITLE
When double clicking the bash script, nothing happens

### ISSUE THREAD

**Issue by BlkPingu** [tangphillip/Imgur-Uploader#12]
It just opens iTerm. That's it. I says "double click" in the readme. Can you clarify the installation process? The installation process seems a bit unclear to me.
I aim on using this as a command line tool.
Why isn't this a homebrew package?

**Comment by tangphillip** [comment]
I'll look into adding this as a homebrew package, but it currently isn't one.

There's no installation process for the shell script, as it's a single file script with no dependencies. If you want to be able to use it from your terminal without typing out the path to the script, copy it to any folder on your terminal's `PATH`.

(To see that list of directories, run `echo $PATH` in your shell. I'd recommend `/usr/local/bin`, as it's likely the right spot for you. To read more about the locations on your `PATH`, check out [this Stack Exchange post](https://unix.stackexchange.com/a/8658).)

**Comment by tangphillip** [comment]
Update on the Homebrew thing—this script doesn't fit the requirements for Homebrew, since it may or may not make the cut for "be used," and definitely doesn't meet the requirement for "have a homepage."

I'm not interested in making a homepage for this tool, but if you'd like to make one, we might be able to get this in Homebrew!

**Comment by BlkPingu** [comment]
I could set you up with a website, but you'd have to host it.

**Comment by tangphillip** [comment]
Oh interesting—from that thread:

> A github readme will also suffice. It’s mostly about having a place users can refer to for more information.

So far, so good on that one! If you'd like to see this tool on homebrew, try [writing a homebrew formula](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md) and submitting it! They frown on authors submitting their own tools. :)
