### ISSUE TITLE
Change license to a free software license

### ISSUE THREAD

**Issue by ShyWest** [tangphillip/Imgur-Uploader#8]
Creative Commons isn't a proper license for software and the Creative Commons Corporation itself encourage people to use free software licenses for such works. <https://creativecommons.org/software/>

The GPL seems the closest one to the Creative Commons Attribution 3.0 Unported, granting the same freedoms and restrictions. <https://gnu.org/licenses/gpl.html>

**Comment by tangphillip** [comment]
Good point! I'll change the license now.

The GPL isn't really that close to CC Attribution 3.0 Unported—it requires all derivative works to be under the GPL as well, and is closer to a copyleft license than a totally permissive license.

I think MIT is closest to what I want, so I'm going with that.
